### ISSUE TITLE
Invoke local

### ISSUE THREAD

**Issue by luisrock** [umihico/docker-selenium-lambda#115]
"Local invocation of lambdas pointing AWS ECR images is not supported" 
when trying `sls invoke local --function demo`

Any hint?

**Comment by umihico** [comment]
Did you try the local invoking before you deploy?

**Comment by luisrock** [comment]
isn't this the usual procedure when developing an application?

**Comment by umihico** [comment]
I would assume the answer is yes.

In deployment procedure, Docker is doing their basic job, which is tagging local image as same URL before they push. After that, docker don't think this is pointing remote repository anymore because exact same tag exists in local. I guess this is how you can fix this. You just need to tag same image uri.

> isn't this the usual procedure when developing an application?
In production applications, yes. But you can just deploy and check my code works within a minute without thinking. You can use more time by customizing (invoking locally) after you are sure that this repository is valuable.

**Comment by luisrock** [comment]
Please don't take my last reply as bad as it appears to me now (re-reading it). It was an honest doubt (I'm a newbie).  Anyway, thanks for helping me. Your repo is very useful.
