### ISSUE TITLE
Issue with auto-update error and request for bug fix

### ISSUE THREAD

**Issue by Satoko310** [umihico/docker-selenium-lambda#174]
Hello @umihico,

Thanks to your docker-selenium-lambda, I am able to use the latest chromedriver, and it has been incredibly helpful.

The auto-update process that is being performed with GitHub Actions has been failure for the past week.
After inspecting the file `auto-update.yml`, I discovered that the problem arises on line 56, where it seems to be related to the recent release of Chrome's beta version with major number 115.  And it appears that there is no chromedriver version available with a major version of 115, which seems to be the root cause of the issue.

I would greatly appreciate it if you could assist in addressing this bug and providing a fix for it. Your support in resolving this matter would be immensely helpful.

Thank you very much for your attention to this matter.

**Comment by umihico** [comment]
Thank you. 

I know fetching https://chromedriver.storage.googleapis.com/LATEST_RELEASE_114 was okay but https://chromedriver.storage.googleapis.com/LATEST_RELEASE_115 is failing today. Also, there are no any references about 115 [here](https://chromedriver.chromium.org/downloads) today. Since there is no chormedriver 115, there is nothing I can do. We need to wait.


I added [another workflow](https://github.com/umihico/docker-selenium-lambda/pull/176) that shows this repository still functionally working with Chromium 114. I believe 114 is good enough for most of purposes

**Comment by Satoko310** [comment]
I understand. Thank you very much for your kind assistance.
