### ISSUE TITLE
Chrome not reachable error.. but only after many runs

### ISSUE THREAD

**Issue by greattypo** [umihico/docker-selenium-lambda#30]
This is a strange one, and I'm honestly not sure if the problem is with this wonderful library or AWS.  Posting here in case it's something to do with the former - thank you so much for any help!

**Steps to repro:**
1. Run the setup commands, including the invocation, exactly from the README (I used `us-west-1`). Everything works great.
2. Set up an EventBridge rule to run your new Lambda function every 2 minutes.
3. Wait 30 minutes

**Result:**
Per CloudWatch logs, the function successfully executes ~14 times, and then begins to fail consistently with one of the following errors: 

`[ERROR] WebDriverException: Message: chrome not reachable` 
and, sometimes:
`[ERROR] WebDriverException: Message: unknown error: cannot create temp dir for unpacking extensions`

**Screenshot:**
<img width="1213" alt="Screen Shot 2022-01-02 at 4 07 45 PM" src="https://user-images.githubusercontent.com/940604/147892853-73d21da1-64ea-403c-a804-729710124c8f.png">

**Comment by umihico** [comment]
@greattypo
Thank you for reporting. AWS Lambda tries to **reuse** container, and it's known behavior that sometimes `/tmp` files remain the same as previous one. This could be buggy reason for Chrome because Chrome cache many files there.

My another repository [pythonista-chromeless](https://github.com/umihico/pythonista-chromeless/) had to deal with the issue. These links below are my solution that. I hope these modifications could help your situations too.

- [wipe /tmp always when start](https://github.com/umihico/pythonista-chromeless/blob/32b29911b81e0b6dcfb37eac8dd62d06c578b9a0/sls/server.py#L17-L27
)
- [randomize the storage location](https://github.com/umihico/pythonista-chromeless/blob/32b29911b81e0b6dcfb37eac8dd62d06c578b9a0/sls/server.py#L127-L130)

(BTW, I want this repository code short and simple as much as possible, then people can read my entire code instead of trusting me, so I'm not planning to insert these advanced modifications)

**Comment by greattypo** [comment]
Wow, thanks for such a helpful response. I've implemented the first one and already notice that the amount of memory used has stopped increasing after each run. Will play around with the storage location next. Really appreciate the suggestion!

**Comment by umihico** [comment]
I changed my mind and modified a little bit. I think this is enough theoretically and we'll see. #31
